[project]
name = "fast-shipment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.133.1",
    "greenlet>=3.3.2",
    "sqlmodel>=0.0.37",
]
